contact_links:
  - name: Provider Request ğŸ•
    url: https://github.com/consumet/extensions/issues/new?assignees=&labels=Provider+Request&template=provider-request.yml&title=%5BProvider+Request%5D%3A+
    about: Request a new provider

  - name: Question ğŸ™‹
    url: https://discord.gg/qTPfvMxzNH
    about: Ask your question or suggestion in Discord server

  - name: Providers list ğŸ”
    url: https://consumet.org/extensions/list/
    about: A list of the available providers
