contact_links:
  - name: ğŸ• Provider Request
    url: https://github.com/consumet/extensions/issues/new?assignees=&labels=provider+request&template=provider-request.yml
    about: Request a new provider

  - name: ğŸ™‹ Question
    url: https://discord.gg/qTPfvMxzNH
    about: Ask your question or suggestion in Discord server

  - name: ğŸ” Providers list
    url: https://consumet.org/extensions/list/
    about: A list of the available providers
